stages:
  packers:
    cmd: ./src/packers/packers.sh
    deps:
    - data/raw/
    - src/packers/
    outs:
    - data/packed/
  crypters_tutorial:
    cmd: clang --target=i686-pc-windows-gnu ./src/crypters/tutorial/decrypter.c 
      -o ./src/crypters/tutorial/decrypter.exe  "-Wl,--entry=__start" 
      -nostartfiles -nostdlib -lkernel32 && python3 
      ./src/crypters/tutorial/crypter.py
    deps:
    - ./data/raw/exe/x86/
    - ./src/crypters/tutorial/crypter.py
    - ./src/crypters/tutorial/decrypter.c
    outs:
    - ./data/crypters/exe/x86/tutorial/
  custom_ablation:
    cmd: ./src/custom/ablation/do_all_folders.sh
    deps:
    - ./data/crypters/exe/x86/code_obfuscation/opaque_ifs/
    - ./data/crypters/exe/x86/idata_obfuscation/opaque_calls/
    - ./data/crypters/exe/x86/multiple_information_reveal/
    - ./data/crypters/exe/x86/tutorial/
    - ./data/packed/exe/x86/mpress/
    - ./data/packed/exe/x86/petite/
    - ./data/packed/exe/x86/upx/default/
    - ./data/packed/exe/x86/upx/lzma/
    - ./src/custom/ablation/
    outs:
    - ./data/custom/ablation/
  multiple_crypters_information_reveal:
    cmd: ./src/crypters/multiple_information_reveal/do_all.sh
    deps:
    - data/raw/exe/x86
    - src/crypters/multiple_information_reveal
    outs:
    - data/crypters/exe/x86/multiple_information_reveal/
  crypter_obfuscation:
    cmd: ./src/crypters/code_obfuscation/do_all.sh
    deps:
    - data/raw/exe/x86
    - src/crypters/code_obfuscation/
    outs:
    - data/crypters/exe/x86/code_obfuscation/
  idata_obfuscation_opaque_calls:
    cmd: ./src/crypters/idata_obfuscation/execute_pipeline.sh
    deps:
    - ./src/lib/
    - data/preprocessed_headers/
    - data/raw/exe/x86/
    - data/usable_headers/
    - src/crypters/idata_obfuscation/
    outs:
    - data/crypters/exe/x86/idata_obfuscation/opaque_calls/
